cloud:
  aws:
    region:
      static: eu-central-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${AWS_KEY}
      secret-key: ${AWS_SECRET}

server:
  servlet:
    context-path: /email